true_love:
  steps:
    - name: build
      container: rust:buster
      cmd: cargo build --release
      env: 
    - name: make cleanable
      container: busybox
      cmd: chmod -R 777 /repo/target
      env:
