true_love:
  steps:
    - name: repo?
      container: busybox
      cmd: ls
      env:
    - name: build
      container: rust:buster
      cmd: cargo build --release
      env: 
    - name: env_check
      container: busybox
      cmd: echo $HELLO
      env:
        HELLO: World!
